### PR TITLE
fix(validation): Return no issues if in scope refsets can't be found

### PR DESCRIPTION
**Pull request by AAAlinaaa**

### CODE REVIEW

**Review by apeteri — APPROVED** [review]
LGTM!

Please apply the same diff to the other MRCM validation rule script as well so it doesn't spend too much time running when it becomes clear that no MRCM rule reference sets apply to the module.

**Comment by apeteri** [comment]
Requesting second review.

**Review by nagyo — APPROVED** [review]
🍏

**Review by cmark — APPROVED** [review]
🥓

**Pull request merged**
