### PR TITLE
ComponentURI unspecified check

### PR DESCRIPTION
**Pull request by AAAlinaaa**

### CODE REVIEW

**Review by cmark — APPROVED** [review]
🥓

**Review by cmark — APPROVED** [review]
🥓

**Review by apeteri — APPROVED** [review]
👍

**Comment by apeteri** [comment]
I found something after merging this PR &ndash; there is an `isUnspecified` check that used the original expression, it should be changed as well: https://github.com/b2ihealthcare/snow-owl/blob/dc1a48004aac8e2805fbcc419aad97d1a9a40656/core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/uri/ComponentURI.java#L97-L100

**Pull request merged**
