### PR TITLE
Remove H2 from embedded dependencies of com.b2international.commons

### PR DESCRIPTION
**Pull request by apeteri**
https://snowowl.atlassian.net/browse/SO-5871

### CODE REVIEW

**Review by cmark — CHANGES_REQUESTED** [review]
While this is okay as it removes the H2 jar, SQL related utilities are still in this repository while they are not being used at all. Would it be possible to move the JdbcUtils class and anything SQL related to the other repository?

**Comment by apeteri** [comment]
I moved the classes to the scripting project.

**Review by cmark — APPROVED** [review]
🥓

**Review by nagyo — APPROVED** [review]
LGTM! 🍏

**Pull request merged**
