### PR TITLE
fix(snomed.reasoner): Add support for annotation properties in DelegateOntology as well

### PR DESCRIPTION
**Pull request by apeteri**

### CODE REVIEW

**Review by nagyo — APPROVED** [review]
LGTM!

**Review by cmark — APPROVED** [review]
This looks okay to me, do we need any additional test cases for this?

**Comment by apeteri** [comment]
@AAAlinaaa added one here:

https://github.com/b2ihealthcare/snow-owl/blob/297f06a127e2164af03b2842459aa086a0a95551/snomed/com.b2international.snowowl.snomed.core.rest.tests/src/com/b2international/snowowl/snomed/core/rest/classification/SnomedClassificationApiTest.java#L587-L622

I think the child concept has a stated IS A relationship due to the test helper and this is why it passed earlier. I'll try to break it then see if the change fixes it 🔧

**Review by cmark — APPROVED** [review]
🥓

**Pull request merged**
