### PR TITLE
Update SnomedConcept.java

### PR DESCRIPTION
**Pull request by eranhash**
Removed redunant parenthesis at lines 149,169

### CODE REVIEW

**Comment by cmark** [comment]
Hey @eranhash,

Thank you for your contribution.
Are you going to add the fix to the third minor code smell here? Or in a new PR?
The next release is about to be released today or next Monday, so these fixes can be included as well if needed. :)

Cheers,
Mark

**Comment by eranhash** [comment]
Hi @cmark
removing redundant parenthesis  in two lines counts as 2 and moving trailing comment is the third, so im done.
sorry that wasn't clear.

thank you for allowing me to make my first steps in the open source community in your project.

Cheers
Eran

**Comment by cmark** [comment]
Hi @eranhash,

Cool, we will merge this PR then.

Thank you and have a nice day,
Mark

**Review by cmark — APPROVED** [review]
LGTM!

**Pull request merged**
