### PR TITLE
fix(index): support loading unindexed fields from documents

### PR DESCRIPTION
**Pull request by cmark**
This resolves problems around exporting query type reference set to RF2.

### CODE REVIEW

**Review by nagyo — APPROVED** [review]
LGTM!

**Review by apeteri — APPROVED** [review]
👍

**Comment by apeteri** [comment]
For nested docs `@Doc(index = false)` is also allowed. Do we want to handle these as well?

**Comment by cmark** [comment]
> For nested docs `@Doc(index = false)` is also allowed. Do we want to handle these as well?

No need for it now, I think. We can introduce it in another PR if needed.

**Pull request merged**
